### ISSUE TITLE
Testbench doesn't bounce

### ISSUE THREAD

**Issue by johnbentcope** [johnbentcope/iron_violet#24]
When the testbench pushes buttons, it doesn't bounce them. It should bounce inputs a little to make sure debouncing works.

**Comment by KaseyHDL** [comment]
I can work on a bouncy task for this

**Comment by KaseyHDL** [comment]
The issue with bouncing in python is that you can only use time.sleep() for as low as 10ms which is a very tiny when compared to a period at 50MHz. I am going to modify the testbench so that instead of buttons being held high for 10 CCs and then low, there is a longer amount of time in which a given button is bounced before staying low.

**Comment by KaseyHDL** [comment]
I'm a python newb so this could be done more gracefully if I can figure out how to pass in a button but here is my solution hope it works:

async def bounce_red(dut, end_state, cycles=5):
  """
  This coroutine bounces the red button.
  """
  
  dut.butt_red.value = end_state
  
  for _ in range(cycles)
    time.sleep(random.randint(0,10)/1000) # Delay between 0 to 10 ms
    dut.butt_red.value = not desired_state

  dut.butt_red.value = end_state

closing issue...
